<a href="https://colab.research.google.com/github/jarvis1200/Tensorflow_Materials/blob/main/Tensorflow_Fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import tensorflow as tf
print(tf.__version__)

2.5.0


In [4]:
## tf .constant

In [5]:
T = tf.constant(10)
T

<tf.Tensor: shape=(), dtype=int32, numpy=10>

In [6]:
V = tf.constant([10,10])
V

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [7]:
V.ndim

1

In [8]:
tensor = tf.constant([[[1,2,3],
                       [2,4,5]],
                      [[1,2,3],
                       [2,4,5]],
                      [[1,2,3],
                       [2,4,5]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[1, 2, 3],
        [2, 4, 5]],

       [[1, 2, 3],
        [2, 4, 5]],

       [[1, 2, 3],
        [2, 4, 5]]], dtype=int32)>

In [9]:
tensor.ndim

3

In [10]:
## tf.variable

In [11]:
changeableTensor= tf.Variable([10,8])
unchangeableTensor = tf.constant([10,8])
changeableTensor, unchangeableTensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  8], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  8], dtype=int32)>)

In [12]:
changeableTensor[0].assign(8)
changeableTensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([8, 8], dtype=int32)>

In [13]:
unchangeableTensor[0].assign(8)
unchangeableTensor

AttributeError: ignored

In [14]:

### Creating random tensor

In [15]:
random1 = tf.random.Generator.from_seed(50)
random1 = random1.uniform(shape = (3,2))
random1

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[0.466465  , 0.05981874],
       [0.40098202, 0.69292355],
       [0.1284684 , 0.22770369]], dtype=float32)>

In [16]:
random2 = tf.random.Generator.from_seed(50)
random2 = random2.normal(shape = (3,2))
random2

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[ 0.45331386,  1.1487608 ],
       [-1.2659091 , -0.47450137],
       [ 2.006022  ,  0.28288034]], dtype=float32)>

In [17]:
random1 == random2

<tf.Tensor: shape=(3, 2), dtype=bool, numpy=
array([[False, False],
       [False, False],
       [False, False]])>

In [18]:
### Shuffling the element

In [19]:
unShuffled = tf.constant([[1,2,3],[3,5,6],[2,7,8]])
unShuffled

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [3, 5, 6],
       [2, 7, 8]], dtype=int32)>

In [20]:
tf.random.shuffle(unShuffled)


<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[2, 7, 8],
       [1, 2, 3],
       [3, 5, 6]], dtype=int32)>

In [21]:
tf.random.shuffle(unShuffled, seed=40)


<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[3, 5, 6],
       [1, 2, 3],
       [2, 7, 8]], dtype=int32)>

In [22]:
tf.random.set_seed(40)

tf.random.shuffle(unShuffled, seed=40)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[2, 7, 8],
       [1, 2, 3],
       [3, 5, 6]], dtype=int32)>

In [23]:
## creating ones and zeros

In [24]:
A = tf.ones([10,7])
A

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [25]:
B = tf.zeros([4,6])
B

<tf.Tensor: shape=(4, 6), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]], dtype=float32)>

In [26]:
### changing Numpy arry into Tensorflow Array

In [27]:
import numpy as np

Q = np.arange(0,30, dtype = int)
Q


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [28]:
Q = tf.constant(Q)
Q

<tf.Tensor: shape=(30,), dtype=int64, numpy=
array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])>

In [29]:
Q = tf.constant(Q, shape=(2,3,5))
Q

<tf.Tensor: shape=(2, 3, 5), dtype=int64, numpy=
array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]],

       [[15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]]])>

In [30]:
Q.ndim

3

In [31]:
## creating Tensor with Shape, Size

In [32]:
Zero = tf.zeros(shape=(2,3,4,5))
Zero

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [33]:
Zero.shape

TensorShape([2, 3, 4, 5])

In [34]:
Zero.ndim

4

In [35]:
tf.size(Zero)

<tf.Tensor: shape=(), dtype=int32, numpy=120>

In [36]:
# getting various attributes from data

print('data type : ',Zero.dtype)
print("No of Dimension : ", Zero.ndim)
print('shape of data : ', Zero.shape)
print('Element in 0axis : ', Zero.shape[0])
print('Element in last axis : ',Zero.shape[-1])
print('total num of data : ', tf.size(Zero).numpy())

data type :  <dtype: 'float32'>
No of Dimension :  4
shape of data :  (2, 3, 4, 5)
Element in 0axis :  2
Element in last axis :  5
total num of data :  120


In [37]:
Zero[:2, :2, :2, :2]


<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [38]:
Zero[:1, :1, :1, :]


<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [39]:
## Expanding Dimension

In [40]:
rank_2_tensor = tf.constant([[10, 7],
                             [3, 4]])

rank_2_tensor.ndim

# Get the last item of each row
rank_2_tensor[:, -1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 4], dtype=int32)>

In [41]:
rank_3_tensor = rank_2_tensor[..., tf.newaxis] # in Python "..." means "all dimensions prior to"
rank_2_tensor, rank_3_tensor, rank_3_tensor.ndim # shape (2, 2), shape (2, 2, 1)

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[10,  7],
        [ 3,  4]], dtype=int32)>,
 <tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
 array([[[10],
         [ 7]],
 
        [[ 3],
         [ 4]]], dtype=int32)>,
 3)

In [42]:
tf.expand_dims(rank_2_tensor, axis=-1) # "-1" means last axis


<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [43]:
 #manipulating Tensors(tensor operations)

In [44]:
tensor = tf.constant([[2,3],[4,7]])
tensor += 5
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 7,  8],
       [ 9, 12]], dtype=int32)>

In [45]:
tensor * 4

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[28, 32],
       [36, 48]], dtype=int32)>

In [46]:

tensor - 5

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[2, 3],
       [4, 7]], dtype=int32)>

In [47]:
tf.multiply(tensor, 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 70,  80],
       [ 90, 120]], dtype=int32)>

In [48]:
tf.add(tensor,10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[17, 18],
       [19, 22]], dtype=int32)>

In [49]:
### Matrix Multipication

In [50]:
tensor ,tf.matmul(tensor,tensor)

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 12]], dtype=int32)>, <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[121, 152],
        [171, 216]], dtype=int32)>)

In [51]:

tensor @ tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121, 152],
       [171, 216]], dtype=int32)>

In [52]:
x = tf.constant([[1,2,3],[4,6,7]])
y = tf.constant([[1,2,3],[4,6,7]])
x @ y

InvalidArgumentError: ignored

In [53]:
x.shape, tf.reshape(y,shape=(3,2))

(TensorShape([2, 3]), <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [6, 7]], dtype=int32)>)

In [54]:

x @ tf.reshape(y,shape=(3,2))

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[25, 31],
       [64, 81]], dtype=int32)>

In [55]:
tf.matmul(x , tf.reshape(y,shape=(3,2)))

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[25, 31],
       [64, 81]], dtype=int32)>

In [56]:
tf.transpose(x), tf.reshape(x, shape= (3,2))

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 4],
        [2, 6],
        [3, 7]], dtype=int32)>, <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [6, 7]], dtype=int32)>)

In [57]:
tf.matmul(tf.transpose(x),y)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[17, 26, 31],
       [26, 40, 48],
       [31, 48, 58]], dtype=int32)>

In [58]:
### Dot product

#matrix multiplication as done using :
#tf.matmul()
#tf.tensordot()

In [59]:
# with transpose
tf.tensordot(x, tf.transpose(y), axes =1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 14,  37],
       [ 37, 101]], dtype=int32)>

In [60]:
# with reshape
tf.tensordot(x, tf.reshape(y, shape=(3,2)), axes= 1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[25, 31],
       [64, 81]], dtype=int32)>

In [61]:

#lets see diff bw reshape and transpose

print('normal : ', x)
print('Reshape : ', tf.reshape(x,shape=(3,2)))
print('transpose : ', tf.transpose(x))

normal :  tf.Tensor(
[[1 2 3]
 [4 6 7]], shape=(2, 3), dtype=int32)
Reshape :  tf.Tensor(
[[1 2]
 [3 4]
 [6 7]], shape=(3, 2), dtype=int32)
transpose :  tf.Tensor(
[[1 4]
 [2 6]
 [3 7]], shape=(3, 2), dtype=int32)


In [62]:
# changing the data type of tensor

In [63]:
a = tf.constant([1.3,4.5])
a.dtype

tf.float32

In [64]:
# float16 get lesser space and run fast so we have to change float32 to float16

In [67]:
D = tf.cast(a, dtype = tf.float16)
D.dtype

tf.float16

In [68]:
# getting the absolute value

In [69]:
q = tf.constant([-7, -9])
q

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([-7, -9], dtype=int32)>

In [71]:
tf.abs(q)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 9], dtype=int32)>

In [72]:
# finding the min , max , sum, mean.

In [74]:
w = tf.constant(np.random.randint(0,700, size = 50))
w

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([391, 246, 271, 577,  69, 175, 189, 556, 421,   0,   8, 123, 536,
       326, 163, 182, 674, 312, 218, 566, 492, 405, 459, 336, 284, 373,
       693, 341, 435, 428, 623, 485, 686, 489, 553, 644, 529, 459, 294,
       490, 540, 690,  17,  76, 428, 555, 299, 432,  58, 263])>

In [76]:
tf.size(w)

<tf.Tensor: shape=(), dtype=int32, numpy=50>

In [77]:
tf.reduce_min(w)

<tf.Tensor: shape=(), dtype=int64, numpy=0>

In [78]:
tf.reduce_max(w)

<tf.Tensor: shape=(), dtype=int64, numpy=693>

In [79]:
tf.reduce_mean(w)

<tf.Tensor: shape=(), dtype=int64, numpy=377>

In [80]:
tf.reduce_sum(w)

<tf.Tensor: shape=(), dtype=int64, numpy=18859>

In [84]:
# to find variance and standard deviation, we have to convert the tensors into float32

In [85]:
e = tf.cast(w,dtype=tf.float32)

In [86]:
tf.math.reduce_variance(e)

<tf.Tensor: shape=(), dtype=float32, numpy=37091.344>

In [87]:
tf.math.reduce_std(e)

<tf.Tensor: shape=(), dtype=float32, numpy=192.59113>

In [88]:
# create a new tensor to find positional min and max

In [90]:
tf.random.set_seed(42)
s = tf.random.uniform(shape = [40])
s

<tf.Tensor: shape=(40,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ],
      dtype=float32)>

In [91]:
#find the maximum position
tf.argmax(s)

<tf.Tensor: shape=(), dtype=int64, numpy=30>

In [92]:
s[tf.argmax(s)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.9485276>

In [93]:
tf.reduce_max(s)

<tf.Tensor: shape=(), dtype=float32, numpy=0.9485276>

In [94]:
#find the minimum position

In [95]:
tf.argmin(s)

<tf.Tensor: shape=(), dtype=int64, numpy=16>

In [96]:
s[tf.argmin(s)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>

In [97]:
tf.reduce_min(s)

<tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>

In [98]:
# squezzing the tensor(removing all single dimensional)

In [101]:
tf.random.set_seed(42)
d = tf.constant(tf.random.uniform(shape=[50]),shape=(1,1,1,1,50))
d

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
           0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
           0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
           0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
           0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
           0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
           0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
           0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
           0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
           0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]]],
      dtype=float32)>

In [102]:
d.shape

TensorShape([1, 1, 1, 1, 50])

In [103]:
d_squeezed = tf.squeeze(d)
d_squeezed, d_squeezed.shape

(<tf.Tensor: shape=(50,), dtype=float32, numpy=
 array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
        0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
        0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
        0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
        0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
        0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
        0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
        0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
        0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
        0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
       dtype=float32)>, TensorShape([50]))

In [104]:
# one hot encoding(convert to numerical coding of tensor)

In [105]:
s = [0,1,2,3]

tf.one_hot(s, depth=4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [106]:
#custom values for one hot

tf.one_hot(s, depth=4, on_value='its me', off_value='not me')

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'its me', b'not me', b'not me', b'not me'],
       [b'not me', b'its me', b'not me', b'not me'],
       [b'not me', b'not me', b'its me', b'not me'],
       [b'not me', b'not me', b'not me', b'its me']], dtype=object)>

In [107]:
# square, log, square root

In [109]:
t = np.arange(1,10)
t

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [110]:
tf.square(t)

<tf.Tensor: shape=(9,), dtype=int64, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81])>

In [111]:
tf.sqrt(tf.cast(t, dtype = tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([1.       , 1.4142135, 1.7320508, 2.       , 2.236068 , 2.4494898,
       2.6457512, 2.828427 , 3.       ], dtype=float32)>

In [114]:
#log

tf.math.log(tf.cast(t, dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

In [115]:
# Manipulating tensor variables with assign and assign_add 

In [118]:
I = tf.Variable(np.arange(0,5))

In [119]:
I.assign([0,1,2,3,5])

<tf.Variable 'UnreadVariable' shape=(5,) dtype=int64, numpy=array([0, 1, 2, 3, 5])>

In [120]:
I.assign_add([10,10,10,10,10])

<tf.Variable 'UnreadVariable' shape=(5,) dtype=int64, numpy=array([10, 11, 12, 13, 15])>

In [121]:
#tensor and Numpy

In [122]:
J = tf.constant(np.array([3,5,6,7]))

In [123]:
np.array(J), type(J.numpy())

(array([3, 5, 6, 7]), numpy.ndarray)

In [124]:
J.numpy()[0]

3

In [125]:
# Tf functions

In [126]:
def func(x,y):
  return x**2 + y**2

x = tf.constant([2,4,5,6])
y = tf.constant([3,5,6,7])
print(func(x,y))

tf.Tensor([13 41 61 85], shape=(4,), dtype=int32)
